# --------------------------------------------------
# finder
# --------------------------------------------------
[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = [
	'nerdfont.vim',
	'fern-renderer-nerdfont.vim',
	'glyph-palette.vim',
	'fern-git-status.vim'
]
hook_add = '''
let g:fern#default_hidden = 1 " show hidden files
let g:fern#renderer = 'nerdfont'
let g:fern#renderer#nerdfont#indent_markers = 1

nnoremap <silent> <Leader>e :<C-u>Fern . -reveal=% -drawer -width=40<CR>

"nnoremap <Plug>(fern-close-drawer) :<C-u>FernDo close -drawer -stay<CR>
"nmap <buffer><silent> <Plug>(fern-action-open-and-close)
"	\ <Plug>(fern-action-open)
"	\ <Plug>(fern-close-drawer)

function! s:fern_preview_init() abort
  nmap <buffer><expr>
        \ <Plug>(fern-my-preview-or-nop)
        \ fern#smart#leaf(
        \   "\<Plug>(fern-action-open:edit)\<C-w>p",
        \   "",
        \ )
  nmap <buffer><expr> j
        \ fern#smart#drawer(
        \   "j\<Plug>(fern-my-preview-or-nop)",
        \   "j",
        \ )
  nmap <buffer><expr> k
        \ fern#smart#drawer(
        \   "k\<Plug>(fern-my-preview-or-nop)",
        \   "k",
        \ )
endfunction

augroup my-fern-preview
  autocmd! *
  autocmd FileType fern call s:fern_preview_init()
augroup END

" You need this otherwise you cannot switch modified buffer
set hidden
'''
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
'''
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
hook_add = '''
nnoremap <silent> <Leader>f :<C-u>FZF<CR>
'''
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']

# --------------------------------------------------
# snippet
# --------------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
let g:sonictemplate_author = 'kaduhiro'
let g:sonictemplate_license = 'MIT'
let g:sonictemplate_vim_template_dir = expand('~/.vim/template')
'''

