#!/bin/sh

export GUM_INPUT_CURSOR_FOREGROUND='#40E0D0'

export GUM_FILTER_MATCH_FOREGROUND='#40E0D0'
export GUM_FILTER_INDICATOR_FOREGROUND='#40E0D0'

export GUM_CHOOSE_CURSOR_PREFIX='[ ] '
export GUM_CHOOSE_UNSELECTED_PREFIX='[ ] '
export GUM_CHOOSE_SELECTED_PREFIX='[*] '

export GUM_CHOOSE_CURSOR_FOREGROUND='#40E0D0'
export GUM_CHOOSE_CURSOR_BACKGROUD='#40E0D0'
export GUM_CHOOSE_SELECTED_FOREGROUND='#20B2AA'

export GUM_CONFIRM_PROMPT_FOREGROUND='#40E0D0'
export GUM_CONFIRM_SELECTED_BACKGROUND='#40E0D0'

